default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_daily_blog_development
  host: localhost
  username: daily-blog
  password: yahya22

test:
  <<: *default
  database: the_daily_blog_test

production:
  <<: *default
  database: the_daily_blog_production
  username: the_daily_blog
  password: <%= ENV["THE_DAILY_BLOG_DATABASE_PASSWORD"] %>
